"""Añadir descripción y estado a TipoDocumento

Revision ID: 11ba50c92b8d
Revises: 2bc3aed264c2
Create Date: 2025-04-06 20:40:43.602988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ba50c92b8d'
down_revision = '2bc3aed264c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
