"""Agregar descripción y estado a unidades

Revision ID: 2881243bc6e9
Revises: 3a33df7cd660
Create Date: 2025-04-06 19:11:03.950552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2881243bc6e9'
down_revision = '3a33df7cd660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
