"""Agregar tabla de historial de contraseñas

Revision ID: 302b96486015
Revises: 8ccb4da870da
Create Date: 2025-03-31 09:55:53.457763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302b96486015'
down_revision = '8ccb4da870da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historial_passwords')
    # ### end Alembic commands ###
