"""Añadir descripción y estado a zonas_economicas

Revision ID: 3a33df7cd660
Revises: c33c25115228
Create Date: 2025-04-06 16:35:19.883701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a33df7cd660'
down_revision = 'c33c25115228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zonas_economicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zonas_economicas', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
