"""Initial migration

Revision ID: 8ccb4da870da
Revises: 
Create Date: 2025-03-20 15:46:46.659365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ccb4da870da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('estados_documento', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('movimientos_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'documentos', ['documento_id'], ['id'])

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('notificaciones_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('notificaciones_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'documentos', ['documento_id'], ['id'])

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('roles_permisos_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('roles_permisos_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.create_foreign_key(None, 'permisos', ['permiso_id'], ['id'])

    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('usuarios_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'personas', ['persona_id'], ['id'])

    with op.batch_alter_table('zonas_economicas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zonas_economicas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('usuarios_ibfk_1', 'personas', ['persona_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tipos_documento', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('roles_permisos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('roles_permisos_ibfk_2', 'permisos', ['permiso_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('roles_permisos_ibfk_1', 'roles', ['rol_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('permisos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notificaciones_ibfk_2', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('notificaciones_ibfk_1', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('movimientos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('movimientos_ibfk_1', 'documentos', ['documento_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('estados_documento', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
