"""Agregar campo ultimo_transferido_por_id a documentos

Revision ID: bc271110dda3
Revises: 11ba50c92b8d
Create Date: 2025-04-07 09:57:06.187622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc271110dda3'
down_revision = '11ba50c92b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_transferido_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['ultimo_transferido_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ultimo_transferido_por_id')

    # ### end Alembic commands ###
