"""Add descripcion column to cargos

Revision ID: c33c25115228
Revises: cee8264fb986
Create Date: 2025-04-05 12:27:53.275989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c33c25115228'
down_revision = 'cee8264fb986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargos', schema=None) as batch_op:
        batch_op.drop_column('activo')
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
